# Generated by Django 3.1.5 on 2021-01-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Profile',
            new_name='profile',
        ),
    ]
