# Generated by Django 3.1.5 on 2021-01-25 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0003_auto_20210125_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='following_profile_id',
        ),
        migrations.RemoveField(
            model_name='following',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='auth.user'),
            preserve_default=False,
        ),
    ]
