# Generated by Django 3.1.5 on 2021-01-26 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0005_auto_20210125_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
